version: "3.9"

services:
  rag-chat-storage-service:
    image: deepa/rag-chat-service:dev
    container_name: rag-chat-storage-service
    env_file:
      - .env.dev
    depends_on:
      postgres:
        condition: service_started
      kafka:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    networks: [backend]
