services:
  rag-chat-storage-service:
    image: deepa/rag-chat-service:latest
    container_name: rag-chat-storage-service
    env_file:
      - .env.prod
    depends_on:
      postgres:
        condition: service_started
      kafka:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    networks: [backend]
