receivers:
  otlp:
    protocols:
      http:

exporters:
  logging:
    loglevel: debug
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, elasticsearch]