server:
  port: 8080

spring:
  application:
    name: api-gateway-service

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always


logging:
  level:
    org.springframework.cloud.gateway: DEBUG