spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: chatstorage-service
          uri: lb://chatstorage-service
          predicates:
            - Path=/ragchatstorage/api/**
          filters:
            - name: RequestRateLimiter
              args:
                # 5 requests/sec with burst capacity of 10
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                keyResolver: "#{@ipKeyResolver}"

  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka}
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30


elasticsearch:
  url: ${ELASTICSEARCH_URL:http://elasticsearch:9200}
logstash:
  host: ${LOGSTASH_HOST:logstash}
  port: ${LOGSTASH_PORT:5001}
kibana:
  url: ${KIBANA_URL:http://kibana:5601}


otel:
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4318/v1/traces}
  service:
    name: ${OTEL_SERVICE_NAME:api-gateway-service-prod}
