package com.xdai.ragchatstorage.audit;

public enum AuditAction {
    SESSION_CREATE,
    SESSION_RENAME,
    SESSION_DELETE,
    SESSION_MARK_FAVORITE,
    MESSAGE_CREATE,
    MESSAGES_LIST_BY_SESSION,
    MESSAGES_DELETE_BY_SESSION,
    MESSAGE_DELETE,
    AUTH_FAILURE,
    RATE_LIMITED,
    SESSIONS_LIST, HEALTH_CHECK
}
